### PR TITLE
Adding lemmas to dependency parses

### PR DESCRIPTION
**Pull request by desilinguist**
- Dependency parses can now contain lemmas in the last column, if NLTK as well as the WordNet corpus for NLTK are both installed. This is done by passing `with_lemmas=True` to the `dep_parse_sentence()` method of a dependency parser object. If either NLTK or the WordNet corpus is not installed, then passing `with_lemmas=True` will print a warning and produce the regular dependency tree without lemmas.
- There are also new unit tests for dependency parsers testing the lemma functionality.
- This PR also contains some other changes pertaining to making the CircleCI builds more efficient and working around the 4GB RAM limit they have on their containers.

@aoifecahill can you please test this out since you are going to be one of the main consumers for this? :)

### CODE REVIEW

**Comment by aoifecahill** [comment]
This works mostly as I would expect it, except for the sentence initial words. I think this needs to be lowercased before being sent to the lemmatizer?

**Comment by desilinguist** [comment]
Good call! Somehow I was under the impression that `morphy` (the wordnet lemmatizer) lowercases internally but it doesn't look like it. Will fix.

**Comment by desilinguist** [comment]
@aoifecahill, it's fixed.

**Comment by aoifecahill** [comment]
Looks good to me, thanks!

**Pull request merged**
